name: Format, Lint & Test

on:
    push:
        branches:
            - development
            - main
    pull_request:
        types:
            - opened
            - reopened
            - synchronize

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    ts-lint:
        name: Format, Lint & Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Prepare
              run: npm install
            - name: Format
              run: npm run format:check
            - name: Lint
              run: npm run lint
            - name: Test
              run: npm run test
